# 多环境配置（dev/prod）支持H2/PostgreSQL切换
spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  apifox:
    enabled: true
    server-url: https://api.apifox.com
    project-id: ${APIFOX_PROJECT_ID}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

file:
  upload-dir: ./uploads

security:
  jwt:
    secret: your-secret-key
    expiration: 86400
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod_db
    username: postgres
    password: postgres